AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python-website-healthchecker

  Sample SAM Template for python-website-healthchecker

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  healthcheckFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: healthcheck/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        healthcheck:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /healthcheck
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  healthcheckApi:
    Description: "API Gateway endpoint URL for Prod stage for healthcheck function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/healthcheck/"
  healthcheckFunction:
    Description: "healthcheck Lambda Function ARN"
    Value: !GetAtt healthcheckFunction.Arn
  healthcheckFunctionIamRole:
    Description: "Implicit IAM Role created for healthcheck function"
    Value: !GetAtt healthcheckFunctionRole.Arn
